backend:
  name: github
  repo: brienpacholec/brien-pacholec

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Posts"
    name: "posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Display", name: "Display", widget: "boolean"}

